---

- hosts: laptop
  force_handlers: true
  roles:
  - role: configure_filesystems
  - role: configure_localization
  - role: configure_hosts
  - role: install_packages

- hosts: laptop
  vars_files:
  - vaulted_vars/secrets
  roles:
  - role: create_users
